### PR TITLE
Improve routes

### PR DESCRIPTION
**Pull request by saadamir3180**
resolves issue #23

### CODE REVIEW

**Review by njmulsqb — CHANGES_REQUESTED** [review]
`http://localhost:3000/our-portfolio/penetration-test-of-mach7t` should be `http://localhost:3000/our-portfolio/vapt/penetration-test-of-mach7t` and same practice should be followed at other areas as well.

**Comment by saadamir3180** [comment]
> `http://localhost:3000/our-portfolio/penetration-test-of-mach7t` should be `http://localhost:3000/our-portfolio/vapt/penetration-test-of-mach7t` and same practice should be followed at other areas as well.

do we also need to do something for blog posts `http://localhost:3000/blogs/unveiling-tecvity-the-future-of-tech-innovation` is the current structure, `http://localhost:3000/blogs/category/company` and `http://localhost:3000/blogs/tag/agency` for blog category and tag respectively.

**Comment by njmulsqb** [comment]
Blog is okay for now.

**Comment by saadamir3180** [comment]
> Blog is okay for now.

i guess you are also expecting me to adjust the breadcrumbs

**Comment by njmulsqb** [comment]
Just the routes for now.

**Pull request merged**
